language: node_js
node_js:
  - "6.9.1"

sudo: required

services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash

install:
  - yarn install

after_script:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
